### ISSUE TITLE
Is it possible to add Length as part of the packet?

### ISSUE THREAD

**Issue by majimboo** [bigeasy/packet#324]
I need to add the length of the packet to the beginning of the packet. Is this possible with packet package?

Let us say 05 00 00 00 00. 05 being the length of the whole packet including the length itself.

Can we have this on the serializer?

Or maybe something like:

```
    serializer.serialize("handshake", { id: 100, gameClientVer: 35, gameUpdateVer: 12, gameDateVer: 435 });
    serializer.serialize("handshake", { length: serializer.sizeOf + 2 });
```

but ofcourse the serializer gets overwritten. So what to do?

**Comment by bigeasy** [comment]
This can now be done with an accumulator. An accumulator might be too heavy for this use case, but it would be a good place to start. There is also a `sizeOf` capability that could be used to calculate the size of a header and it should be performant.
