### ISSUE TITLE
Bit packed alternation

### ISSUE THREAD

**Issue by platy** [bigeasy/packet#354]
I've just found packet and started using it, and I'm already finding it great.

I have a case of a Type/Length/Value encoding for a numeric value. So it starts with a byte `b8{b5 => type, b3 => length}` and then is followed by `b<8*length>`. If the length were not bit packed I could either use alternation or a length-encoded-array to get the value. 

But I don't think its possible in this case so instead I'm extracting the type & length encoding and then setting the next extractor based on the length value - it's pretty messy - is there another way using transformers or something?

**Comment by l0oky** [comment]
I was thinking the same thing. +1 for the question

**Comment by bigeasy** [comment]
Should be possible with calculated array lengths in the new language.
