### ISSUE TITLE
question about array

### ISSUE THREAD

**Issue by openStove** [bigeasy/packet#359]
It a question, but I don't know where to ask...  sorry

I have a couple of fields to extract, that are fix,
after that, I have the number of values coming next, and the corresponding number of values (that is variable according to the number before)...

How do I make this, is it what you mentioned under "Length Encoded Arrays" ?

**Comment by l0oky** [comment]
This module has that feature, https://github.com/deoxxa/dissolve
I couldn't get it working with [bigeasy/packet](https://github.com/bigeasy/packet)

**Comment by bigeasy** [comment]
This can now be done with length encoded arrays. If the length encoding is not immediately before the series of values you can use a calculated array.
