### ISSUE TITLE
Nested length-encoded arrays ?

### ISSUE THREAD

**Issue by roblabla** [bigeasy/packet#81]
I would need the ability to do nested length-encoded array. Something like 

``` javascript
"b32/{b16/b8}"
```

would decode into an array containing arrays of bytes. The idea is to decode a list of strings. Is this do-able ?

Furthermore, Having the ability to specify length-encoded arrays of multiple items such as 

``` javascript
"b32/{b16, b16, b32}"
```

Which would mean an array of structures of 2 shorts and 1 int.

**Comment by bigeasy** [comment]
On the way.
